/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package git.sr.ht/~cdcarter/mage-go/cmd/pylib */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "decision_spec_ffi.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"

#line 15 "main.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"

#line 3 "text_rollout.go"

#include <stdlib.h>
#include "abi.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int32_t MageRegisterDecisionSpecTokens(MageDecisionSpecTokens* tables);
extern void MageReleaseBatchHandle(int64_t handle);
extern MageEncodeResult MageEncodeDecisionSpec(MageBatchRequest* req, int32_t* stateTokenLensPtr, MagePackedSpecOutputs* specOut, int64_t* handleOut);
extern int32_t MageDecisionMaskNext(int64_t batchHandle, int32_t* prefixTokensPtr, int32_t* prefixPointersPtr, int32_t* prefixLensPtr, int32_t batchSize, int32_t prefixLenMax, int32_t grammarVocabSizeArg, int32_t nAnchorsMax, uint8_t* outVocabMaskPtr, uint8_t* outPointerMaskPtr);
extern int32_t MagePackCombinedTokens(int32_t n, int32_t tokenCapacity, int32_t maxCardRefs, MagePackedTokenAssemblerOutputs* packed, MagePackedSpecOutputs* spec);

/* Return type for MageNewGame */
struct MageNewGame_return {
	int64_t r0; /* id */
	char* r1; /* resp */
};
extern struct MageNewGame_return MageNewGame(char* cfgJSON);
extern char* MageState(int64_t id);
extern char* MageLegal(int64_t id);
extern char* MageStep(int64_t id, char* actionJSON);
extern void MageFree(int64_t id);
extern void MageFreeString(char* s);
extern char* MageRegisteredCards(void);
extern char* MageRegisteredManaCosts(void);
extern char* MageSetCardNameRows(char* cardNameRowsJSON);
extern MageEncodeResult MageBatchPoll(MageBatchRequest* req, MageBatchPollOutputs* out);
extern MageEncodeResult MageBatchStepByChoice(MageStepChoiceRequest* req);
extern MageEncodeResult MageBatchStepByDecoderAction(MageDecoderStepRequest* req);
extern MageEncodeResult MageEncodeBatch(MageBatchRequest* req, MageEncodeConfig* cfg, MageEncodeOutputs* out);
extern char* MageNativeTimingSummary(int32_t reset);
extern int32_t MageRegisterTokenTables(MageTokenTables* tables);
extern char* MageTokenTableSummary(void);
extern char* MageTokenTableLookup(int32_t kind, int32_t k0, int32_t k1);
extern char* MageEncodeTimingSummary(int32_t reset);
extern MageEncodeResult MageEncodeTokensPacked(MageBatchRequest* req, MageEncodeConfig* cfg, MageEncodeOutputs* out, MageTokenAssemblerConfig* tokCfg, MagePackedTokenAssemblerOutputs* packedOut);
extern MageEncodeResult MageDrainSPRBoundaryTokensPacked(MageSprEventTokenRequest* req, MageEncodeConfig* cfg, MageTokenAssemblerConfig* tokCfg, MagePackedTokenAssemblerOutputs* packedOut, MageSprEventOutputs* sprOut);
extern int64_t MagePendingPlayer(int64_t id);
extern int64_t MageIsOver(int64_t id);
extern char* MageWinner(int64_t id);
extern MageEncodeResult MageStartTextRollout(MageTextRolloutStartRequest* req);
extern MageEncodeResult MageAddTextRolloutGames(MageTextRolloutStartRequest* req);
extern MageTextReadyBatchResult MageNextTextInferenceBatch(int64_t maxRows, int64_t timeoutMS, MageTextReadyBatchOutputs* out);
extern MageEncodeResult MageSubmitTextChoices(MageTextChoiceSubmitRequest* req);
extern int32_t MageStopTextRollout(int32_t waitForActive);

#ifdef __cplusplus
}
#endif
